import Navbar from "./components/Navbar/page";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Survey Faktor Studi S2 di Luar Negeri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" bg-secondary">
      <body className={`${poppins.className} container mx-auto text-primary`}>
        <Navbar />
        <div className="mt-24 w-[90%] mx-auto mb-10   ">{children}</div>
      </body>
    </html>
  );
}
